import os 
from dotenv import load_dotenv
from generate import generate_email
from send import send_email

load_dotenv()


# Configuration

TOPIC = "How to get better at Leetcoding"
AUDIENCE = "Tech enthusiasts and professionals"
TONE = "Informative and engaging"
RECIPIENTS = ["saltoanthony13@gmail.com"]


#Run the email generation and sending process

if __name__ == "__main__":
    #Generate email content

    print("Generating email...")
    email_body = generate_email(TOPIC, AUDIENCE, TONE)
    print("Email generated successfully!")

    #First line generated by Gemini, is the subject line, rest is the body
    lines = email_body.strip().split("\n")
    subject = lines[0].replace("Subject:", "").strip()
    body = "\n".join(lines[1:]).strip()

    print(f"Subject: {subject}")
    print("Sending...")

    for recipient in RECIPIENTS:
        send_email(to=recipient, subject=subject, body=body)

    print("Done!")